// The demo project's knowledge, loaded from a versioned static bundle.
//
// The bundle is generated by tools/demo-bundle/generate.mjs from one pinned commit of
// datatug/datatug-demo-projects (tools/demo-bundle/pin.json). Nothing here is hand-written project
// knowledge: the saved query, the Chinook schema, the Country entity mapping and the attribution all
// come from that commit. `pnpm demo:bundle:check` fails when the bundle and the pin drift apart.
import type { IQueryDef } from '../models/definition/query-def';
import { QueryType } from '../models/definition/query-def';
import bundleJson from './bundle/demo-project.bundle.json';
import { DEMO_STATIC_DATA_PATH, type DemoDataSource } from './demo-config';

export interface DemoAttribution {
  readonly id: string;
  readonly what: string;
  readonly text: string;
  readonly license: string;
  readonly url: string;
}

export interface DemoSourceFile {
  readonly id: string;
  readonly file: string;
  readonly rows: number;
  readonly columns: readonly string[];
  readonly sha256: string;
  readonly origin: string;
}

export interface DemoFieldMapping { readonly source: string; readonly collection: string; readonly column: string }

export interface DemoBundle {
  readonly bundleVersion: number;
  readonly pin: {
    readonly repository: string;
    readonly commit: string;
    readonly project: string;
    readonly chinook: { readonly repository: string; readonly revision: string; readonly path: string; readonly sha256: string };
  };
  readonly attribution: readonly DemoAttribution[];
  readonly schema: { readonly chinook: Readonly<Record<string, readonly string[]>> };
  readonly entities: { readonly Country: { readonly fields: readonly { readonly id: string; readonly mappings: readonly DemoFieldMapping[] }[] } };
  readonly queries: Readonly<Record<string, DemoSavedQuery>>;
  readonly data: readonly DemoSourceFile[];
  readonly sourceBlobs: Readonly<Record<string, string>>;
}

export interface DemoSavedQuery {
  readonly id: string;
  readonly title: string;
  readonly purpose: string;
  readonly dtql: string;
  readonly federation: { readonly ovdbBaseUrl: string; readonly tables: readonly { readonly name: string; readonly database: string; readonly fields: readonly string[] }[] };
  readonly recordsets: readonly { readonly columns: readonly { readonly name: string; readonly type: string }[] }[];
}

export const demoBundle = bundleJson as unknown as DemoBundle;

/** The saved query's path inside the project, the way a person would name it. */
export const HERO_QUERY_ID = 'sales/chinook-sales-per-capita';

/** A short, stable id for the bundle's content: appended to static file URLs so a new bundle is never served stale. */
export function demoBundleVersion(bundle: DemoBundle = demoBundle): string {
  return bundle.data.map((source) => source.sha256.slice(0, 8)).join('-');
}

export function savedQuery(id: string, bundle: DemoBundle = demoBundle): DemoSavedQuery {
  const query = bundle.queries[id];
  if (!query) throw new Error(`The demo project has no saved query ${id}.`);
  return query;
}

/** Where the executor should read from, and what to tell it when that is the static adapter. */
export interface DemoSourceRuntime {
  readonly baseUrl: string;
  readonly staticSource?: { readonly baseUrl: string; readonly version: string };
  readonly label: string;
}

export function demoSourceRuntime(source: DemoDataSource, origin: string, bundle: DemoBundle = demoBundle): DemoSourceRuntime {
  if (source.kind === 'ovdb') return { baseUrl: source.baseUrl, label: new URL(source.baseUrl).host };
  const baseUrl = `${origin}${DEMO_STATIC_DATA_PATH}`;
  return { baseUrl, staticSource: { baseUrl, version: demoBundleVersion(bundle) }, label: 'static files published with the app' };
}

/** The saved query as the federated executor wants it, pointed at the configured data source. */
export function queryDefinition(id: string, runtime: DemoSourceRuntime, bundle: DemoBundle = demoBundle): IQueryDef {
  const query = savedQuery(id, bundle);
  return {
    id: query.id,
    title: query.title,
    request: { queryType: QueryType.DTQL, text: query.dtql },
    federation: { ovdbBaseUrl: runtime.baseUrl, tables: query.federation.tables },
    recordsets: query.recordsets,
  } as unknown as IQueryDef;
}
