// The demo's static data adapter.
//
// Production has no hosted OVDB database for the demo's reference data yet (the public Chinook server
// has no `geo` database), so the demo can read the same records from static JSON published with the app.
// This module answers the OVDB wire protocol the federated executor speaks (POST /v1/databases/<db>/dtql
// with paging headers) from those files, so the join, the grouping and the arithmetic still run in the
// browser engine through `runFederatedQuery`: only the *source of the rows* differs.
//
// Switching to hosted OVDB later means setting the demo config's data source to `{ kind: 'ovdb', baseUrl }`
// and deleting this adapter's use; nothing else in the demo changes. See demo-config.ts.
//
// The files are generated by tools/demo-bundle/generate.mjs from the pinned demo-project commit and are
// `{ key, data }[]` per collection: the shape an OVDB server returns.

/** Where the static files live: `<baseUrl>/<database>/<collection>.json`. */
export interface StaticOvdbSource {
  readonly baseUrl: string;
  /** Appended as `?v=` so a new bundle is never served from an old cache entry. */
  readonly version?: string;
}

interface Row { readonly key: string; readonly data: Record<string, unknown> }
interface OrderBy { readonly field: string; readonly desc?: boolean }

const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });

function compare(a: unknown, b: unknown): number {
  if (a === b) return 0;
  if (a === null || a === undefined) return -1;
  if (b === null || b === undefined) return 1;
  if (typeof a === 'number' && typeof b === 'number') return a - b;
  return String(a) < String(b) ? -1 : 1;
}

/** A `fetch` that serves the OVDB snapshot-paging protocol from static JSON files. */
export function createStaticOvdbFetch(source: StaticOvdbSource, realFetch: typeof fetch = (input, init) => fetch(input, init)): typeof fetch {
  const base = source.baseUrl.replace(/\/$/, '');
  const files = new Map<string, Promise<readonly Row[]>>();
  const load = (database: string, collection: string): Promise<readonly Row[]> => {
    const path = `${database}/${collection}.json`;
    let rows = files.get(path);
    if (!rows) {
      const suffix = source.version ? `?v=${encodeURIComponent(source.version)}` : '';
      rows = realFetch(`${base}/${path}${suffix}`, { headers: { Accept: 'application/json' } }).then(async (response) => {
        if (!response.ok) throw new Error(`static source ${path} failed (${response.status})`);
        return await response.json() as Row[];
      });
      rows.catch(() => files.delete(path));
      files.set(path, rows);
    }
    return rows;
  };

  return async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    const match = new RegExp(`^${base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/v1/databases/([^/]+)/dtql$`).exec(url);
    if (!match || init?.method !== 'POST') return json({ error: 'not found' }, 404);
    const headers = new Headers(init.headers);
    if (headers.get('OVDB-Page-Close') === 'true') return new Response(null, { status: 204 });
    const request = JSON.parse(String(init.body ?? '{}')) as { from?: { name?: string }; orderBy?: readonly OrderBy[] };
    const name = request.from?.name;
    if (!name || !/^[A-Za-z0-9_-]+$/.test(name)) return json({ error: 'unknown collection' }, 404);
    let rows: readonly Row[];
    try { rows = await load(decodeURIComponent(match[1]), name); }
    catch { return json({ error: 'unknown collection' }, 404); }
    if (request.orderBy?.length) {
      rows = [...rows].sort((left, right) => {
        for (const order of request.orderBy ?? []) {
          const result = compare(left.data[order.field], right.data[order.field]);
          if (result) return order.desc ? -result : result;
        }
        return 0;
      });
    }
    const size = Math.max(1, Number(headers.get('OVDB-Page-Size')) || 500);
    const start = Number(headers.get('OVDB-Page-Token')?.replace('page:', '') ?? 0) || 0;
    const end = Math.min(start + size, rows.length);
    return json({
      records: rows.slice(start, end),
      snapshotToken: `static:${match[1]}`,
      ...(end < rows.length ? { nextPageToken: `page:${end}` } : {}),
    });
  };
}
