name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
  merge_group:
    paths-ignore:
      - 'docs/**'

permissions:
  actions: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v5

      - name: nx lint affected
        run: pnpm nx affected --target=lint --base=${{ env.NX_BASE }} --parallel=8

      - name: nx build affected
        run: pnpm nx affected --target=build --base=${{ env.NX_BASE }} --parallel=8

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v5

      - name: Cache Vite dependency pre-bundle
        uses: actions/cache@v5
        with:
          path: node_modules/.vite
          key: vite-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            vite-${{ runner.os }}-

      - name: nx test affected
        run: pnpm nx affected --target=test --parallel=4 --base=${{ env.NX_BASE }}
